---
kind: List
apiVersion: v1
metadata:
  name: hello-service-complete-example
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: hello-service1
  spec:
    selector:
      name: hello-openshift
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    type: NodePort
- kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-1
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: nodeport-pod-1
      image: bmeng/hello-openshift
      env:
      - name: RESPONSE
        value: nodeport-pod-1
      ports:
      - containerPort: 8080
      - containerPort: 443
- kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-2
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: nodeport-pod-2
      image: bmeng/hello-openshift
      env:
      - name: RESPONSE
        value: nodeport-pod-2
      ports:
      - containerPort: 8080
      - containerPort: 443
