---
kind: List
apiVersion: v1
metadata:
  name: hello-service-complete-example
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: hello-service1
  spec:
    selector:
      name: hello-openshift
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    type: NodePort
- kind: Service
  apiVersion: v1
  metadata:
    name: hello-service2
  spec:
    selector:
      name: hello-openshift
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    type: NodePort
- kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-1
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: hello-pod-container-1
      image: bmeng/hello-openshift
      env:
      - name: RESPONSE
        value: hello-pod-container-1
      ports:
      - containerPort: 8080
      - containerPort: 443
- kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-2
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: hello-pod-container-2
      image: bmeng/hello-openshift
      env:
      - name: RESPONSE
        value: hello-pod-container-2
      ports:
      - containerPort: 8080
      - containerPort: 443
- kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-3
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: hello-pod-container-3
      image: bmeng/hello-openshift
      env:
      - name: RESPONSE
        value: hello-pod-container-3
      ports:
      - containerPort: 8080
      - containerPort: 443
- kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-4
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: hello-pod-container-4
      image: bmeng/hello-openshift
      env:
      - name: RESPONSE
        value: hello-pod-container-4
      ports:
      - containerPort: 8080
      - containerPort: 443
