apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata: 
  name: macvlan-bridge-whereabouts-v6
spec: 
  config: '{
      "cniVersion": "0.3.0",
      "name": "whereabouts",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "fd:dead:beef:1::1-fd:dead:beef:1::4/64"
      }
}'
