apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: whereabouts-overlapping
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.22.0/30",
        "log_file" : "/tmp/whereabouts.log",
        "log_level" : "debug"
      }
    }'
