#oc new-project test1
#oc adm policy add-scc-to-user -z default hostnetwork -n test1
#oc create -f https://raw.githubusercontent.com/weliang1/Openshift_Networking/master/Features/Pod/debug-network-pod2.yaml

---
kind: List
apiVersion: v1
metadata:
  name: test-pods
items:
- kind: Pod
  apiVersion: v1
  metadata:
    name: debug-network-pod2
    labels:
      name: test-openshift
  spec:
    hostNetwork: true
    containers:
    - name: debug-network-pod2
      image: weliang/test-pod
      securityContext:
        privileged: true
        capabilities:
          add: ["NET_ADMIN"]
      command: ['sh', '-c', 'echo Hello! && sleep 3600']
      ports:
      - containerPort: 8080
      - containerPort: 443
