## This pod will continue pinging yahoo.com and facebook.com 5 times and sleep 2 seconds.
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: ping-pod
    name: ping-pod
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: ping-pod
      spec:
        containers:
        - command: 
          - "sh"
          - "-c"
          - "while true; do echo \"$(date): BROADCASTING ARP REQUEST\"; ping -c 5 yahoo.com; ping -c 5 facebook.com; sleep 2; done"
          name: ping-pod
          image: aosqe/pod-for-ping
        restartPolicy: Always
