apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-pod
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: blue-pod
    spec:
      containers:
      - name: blue-pod
        image: bmeng/hello-openshift
        env:
        - name: RESPONSE
          value: Hello blue-pod
        ports:
        - containerPort: 8080
        - containerPort: 443
