apiVersion: v1
kind: Pod
metadata:
  name: egress-redirect-pod
  labels:
    name: egress-redirect-pod
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egress-router-pod
    image: registry.redhat.io/openshift4/ose-egress-router 
    imagePullPolicy:  IfNotPresent
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE
      value: 10.0.149.93
    - name: EGRESS_GATEWAY
      value: 10.0.151.254
    - name: EGRESS_DESTINATION 
      value:  172.217.7.142
    - name: EGRESS_ROUTER_MODE
      value: init
  containers:
  - name: egressrouter-redirect-pod
    image: registry.redhat.io/openshift4/ose-pod
    imagePullPolicy:  IfNotPresent
  nodeSelector:
    app:  egressrouter
