apiVersion: v1
kind: Pod
metadata:
  name: egressrouter-redirect-pod
  labels:
    name: egressrouter-redirect-pod
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egress-router
    image: openshift3/ose-egress-router 
    imagePullPolicy:  IfNotPresent
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE
      value: 172.31.249.18
    - name: EGRESS_GATEWAY
      value: 172.31.248.1
    - name: EGRESS_DESTINATION 
      value:  172.217.7.142
    - name: EGRESS_ROUTER_MODE
      value: init
  containers:
  - name: egress-pod
    image: openshift3/ose-pod
    imagePullPolicy:  IfNotPresent
  nodeSelector:
    app:  egressrouter
