apiVersion: v1
kind: Pod
metadata:
  name: egress-http-proxy-pod
  labels:
    name: egress-http-proxy-pod
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egress-router-setup
    imagePullPolicy: IfNotPresent
    image: registry.redhat.io/openshift4/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE
      value: 192.168.2.187
    - name: EGRESS_GATEWAY
      value: 192.168.0.1
    - name: EGRESS_ROUTER_MODE
      value: http-proxy
  containers:
  - name: egress-http-proxy-pod
    imagePullPolicy: IfNotPresent
    image: registry.redhat.io/openshift4/ose-egress-http-proxy
    env:
    - name: EGRESS_HTTP_PROXY_DESTINATION
      value: |
        !*.redhat.com
        !69.172.200.235/32
        !www.cisco.com
        *
  nodeSelector:
    app: egressrouter-http
      
