---                                                                            
apiVersion: "k8s.cni.cncf.io/v1"                                               
kind: NetworkAttachmentDefinition                                              
metadata:                                                                      
  name: ovn-egressrouter-redirect                                                         
spec:                                                                             
  config: '{                                                                      
    "cniVersion": "0.4.0",                                                                                                                                 
    "type": "egress-router",                                                      
    "name": "ovn-egressrouter-redirect",                                                      
    "ip": {                                                                       
       "addresses":[
         "192.168.10.99/24"
      ],
      "destinations":[
         "10.0.3.0/32"
      ],
      "gateway":"192.168.10.254"                                                
      }                                                                           
    }'
