apiVersion: "k8s.cni.cncf.io/v1" 
kind: NetworkAttachmentDefinition 
metadata: 
  name: ovn-egressrouter-redirect 
spec: 
  config: '{ 
    "cniVersion": "0.4.0", 
    "type": "egress-router", 
    "name": "ovn-egressrouter-redirect", 
    "ip": { 
      "addresses": [ 
        "10.0.0.0/8" 
        ], 
      "destinations": [ 
        "172.217.7.206/32" 
      ], 
      "gateway": "10.0.128.1" 
      } 
    }'
