apiVersion: v1
kind: Pod
metadata:
  name: egress-router-pod
  labels:
    name: egress-router-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: egress-router
spec:
  containers:
    - name: egress-router-pod
      image: quay.io/openshift/origin-egress-router-cni:latest
      securityContext:
        privileged: true
  volumes:
    - name: egress-router
      configMap:
        name: egress-router
        key: destination
