---
kind: List
apiVersion: v1
metadata:
  name: external-ip
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: external-ip
  spec:
    selector:
      name: external-ip
    ports:
    - protocol: TCP
      port: 27018
      targetPort: 8080
    externalIPs:
    - 10.0.76.163
