apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sctpserver
  template:
    metadata:
      labels:
        app: sctpserver
    spec:
      containers:
      - name: sctpserver
        image: quay.io/openshifttest/hello-sdn@sha256:d5785550cf77b7932b090fcd1a2625472912fb3189d5973f177a5a2c347a1f95
