apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctpclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sctpclient
  template:
    metadata:
      labels:
        app: sctpclient
    spec:
      containers:
      - name: sctpclient
        image: quay.io/openshifttest/ubi@sha256:cd014e94a9a2af4946fc1697be604feb97313a3ceb5b4d821253fcdb6b6159ee 
        command: ["/bin/sh", "-c"]
        args:
          ["dnf install -y nc && sleep inf"]
