apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctpserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sctpserver
  template:
    metadata:
      labels:
        app: sctpserver
    spec:
      containers:
        - name: sctpserver
          image: quay.io/openshifttest/ubi@sha256:cd014e94a9a2af4946fc1697be604feb97313a3ceb5b4d821253fcdb6b6159ee 
          command: ["/bin/sh", "-c"]
          args:
            ["dnf install -y nc && sleep inf"]
          ports:
            - containerPort: 30102
              name: sctpserver
              protocol: SCTP
